### ISSUE TITLE
Change text in popup message shown when source is not selected

### ISSUE THREAD

**Issue by alokmodak** [alokmodak/DashboardAutomation#11]
The message in the popup should be clear with clear indication of next steps to take.
Please change the text to say "Please select Data Source".

![popup](https://cloud.githubusercontent.com/assets/9718614/8183908/ca615fbc-1458-11e5-86f6-9a9b9d749399.JPG)

**Comment by Jitendra-Deshmukh** [comment]
Changed to "Please Select Data Source"

Fixed.
