### ISSUE TITLE
Error message is not clear

### ISSUE THREAD

**Issue by alokmodak** [alokmodak/DashboardAutomation#13]
When the required template/output file is not present, the error message should clearly indicate that "File 'MoS KPI Summary.xlsx' not found.

![popup1](https://cloud.githubusercontent.com/assets/9718614/8184267/19be671a-145b-11e5-9a9d-a3a5d020caaa.JPG)

**Comment by Jitendra-Deshmukh** [comment]
File names are added in the messagebox. 
Fixed.
