### ISSUE TITLE
Date picker not working

### ISSUE THREAD

**Issue by alokmodak** [alokmodak/DashboardAutomation#2]

**Comment by Jitendra-Deshmukh** [comment]
the issue is with the reference library used by Excel, a new reference "Microsoft Visual Basic for application extensibility 5.3" is set to resolve this issue.
compatibility testing is remained with other machines.

reference setting >> open excel > press F11 > tools > references

**Comment by Jitendra-Deshmukh** [comment]
Compatibility testing is done, Issue resolved. 

time taken increased.
