### ISSUE TITLE
Filename missing

### ISSUE THREAD

**Issue by alokmodak** [alokmodak/DashboardAutomation#21]
![inputfilemissing](https://cloud.githubusercontent.com/assets/9718614/8297808/51dfd9e4-197e-11e5-8593-648be00aafd8.JPG)
The attached popup box does not show the name of the file visible in the folder.
Either show the filename you found in the folder or
just show a message saying that the file with the format xxx.xlsx not found

**Comment by Jitendra-Deshmukh** [comment]
corrected to
![image](https://cloud.githubusercontent.com/assets/12895705/8303094/0ce6c470-19b9-11e5-8402-32faabd046db.png)
