### ISSUE TITLE
Change in input files required

### ISSUE THREAD

**Issue by alokmodak** [alokmodak/DashboardAutomation#23]
Change the filename in (1) as: Service Scorecard F 6.1_MonthYear.xlsm
Correct filename in (5) to Escalations_Overview_ALL BIUs.xlsx

Following are missing in the list:
(1) Escalations_Overview_All BIUs.xlsx
(2) Files related to warranty cost are missing

**Comment by Jitendra-Deshmukh** [comment]
Input Files Names are changed in the Label accordingly.
